### ISSUE TITLE
UI error during install on github

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#2067]
introduced by https://github.com/CactuseSecurity/firewall-orchestrator/pull/2065 (json export for resolved changes)

action: https://github.com/CactuseSecurity/firewall-orchestrator/actions/runs/5006117133

not seen on local installs

same errors also occur for certification.razor page
```
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1544,150): error CS0400: The type or namespace name 'TabSet' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(218,55): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.TabSet' to 'TabSet?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1553,158): error CS0400: The type or namespace name 'AnchorNavToRSB' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(218,82): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.AnchorNavToRSB' to 'AnchorNavToRSB?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1603,150): error CS0400: The type or namespace name 'TabSet' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(219,47): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.TabSet' to 'TabSet?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
```

#### There seems to be an issue with the standard rule report
Now got a second error during debugging when generating rule report:

```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in FWO.Report.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at FWO.Ui.Display.RuleDisplayHtml.NetworkLocationToHtml(NetworkLocation userNetworkObject, Int32 mgmtId, OutputLocation location, String style, ReportType reportType) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 103
   at FWO.Ui.Display.RuleDisplayHtml.<>c__DisplayClass13_0.<DisplaySourceOrDestination>b__0(NetworkLocation networkLocation) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 132
   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
   at FWO.Ui.Display.RuleDisplayHtml.DisplaySourceOrDestination(Rule rule, OutputLocation location, ReportType reportType, String style, Boolean isSource) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 132
   at FWO.Ui.Display.RuleDisplayHtml.DisplayDestination(Rule rule, OutputLocation location, ReportType reportType, String style) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 28
   at FWO.Ui.Pages.Reporting.Reports.RulesReport.<>c__DisplayClass0_12.<BuildRenderTree>b__61(RenderTreeBuilder __builder5) in /home/tim/dev/firewall-orchestrator/roles/ui/files/FWO.UI/Pages/Reporting/Reports/RulesReport.razor:line 131
   at BlazorTable.Table`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& 
```

And also during rule report generation in a fresh install in the browser:
```
razor.server.js:1 [2023-05-18T11:28:12.414Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
log @ blazor.server.js:1
blazor.server.js:1 [2023-05-18T11:28:12.415Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52089)
    at kt._sendMessage (blazor.server.js:1:68724)
    at kt._sendWithProtocol (blazor.server.js:1:68765)
    at kt.send (blazor.server.js:1:68873)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:131829)
    at w (blazor.server.js:1:2164)
    at C.invokeMethodAsync (blazor.server.js:1:4014)
    at window.js:14:70
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52089)
    at kt._sendMessage (blazor.server.js:1:68724)
    at kt._sendWithProtocol (blazor.server.js:1:68765)
    at kt.send (blazor.server.js:1:68873)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:131829)
    at w (blazor.server.js:1:2164)
    at C.invokeMethodAsync (blazor.server.js:1:4014)
    at window.js:10:71
```

**Comment by tpurschke** [comment]
yes, can confirm that the reporting issue is solved, but the github install error remains unchanged.

**Comment by tpurschke** [comment]
fixed for ubu 20.04
not fixing for ubu 22.04 - disabled respective action
