### ISSUE TITLE
RestSharp Update to v107 (was: warnings and errors during dotnet build process)

### ISSUE THREAD

**Issue by tpurschke** [CactuseSecurity/firewall-orchestrator#1411]
- [x] warning about missing  '--self-contained' or '--no-self-contained' option
- [x] missing project reference in .sln file for autodiscovery
- [x] error after upgrading restsharp to v107:  `/usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(29,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]`

full build log:

```
    Restored /usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj (in 4.88 sec).
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Config.Api/FWO.Config.Api.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Config.File/FWO.Config.File.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Logging/FWO.Logging.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      FWO.Logging -> /usr/local/fworch/lib/files/FWO.Logging/bin/Release/net6.0/FWO.Logging.dll
      FWO.Config.File -> /usr/local/fworch/lib/files/FWO.Config.File/bin/Release/net6.0/FWO.Config.File.dll
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Middleware/FWO.Middleware.csproj]
      FWO.Middleware -> /usr/local/fworch/lib/files/FWO.Middleware/bin/Release/net6.0/FWO.Middleware.dll
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Report/FWO.Report.csproj]
    /usr/share/dotnet/sdk/6.0.101/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(1110,5): warning NETSDK1179: One of '--self-contained' or '--no-self-contained' options are required when '--runtime' is used. [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Api.Client/ApiSubscription.cs(31,21): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Api.Client/APIConnection.cs(125,25): warning CS0162: Unreachable code detected [/usr/local/fworch/lib/files/FWO.Api.Client/FWO.Api.Client.csproj]
      FWO.Api.Client -> /usr/local/fworch/lib/files/FWO.Api.Client/bin/Release/net6.0/FWO.Api.Client.dll
      FWO.Report.Filter -> /usr/local/fworch/lib/files/FWO.Report.Filter/bin/Release/net6.0/FWO.Report.Filter.dll
      FWO.Config.Api -> /usr/local/fworch/lib/files/FWO.Config.Api/bin/Release/net6.0/FWO.Config.Api.dll
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(29,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(36,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(43,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(50,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(57,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(64,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(71,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(78,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(84,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(91,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(97,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(104,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(111,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(118,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(125,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(132,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(139,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(146,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(153,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(160,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(167,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(174,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(181,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(188,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(195,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(202,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(209,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.Middleware.Client/MiddlewareClient.cs(216,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.Middleware.Client/FWO.Middleware.Client.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(29,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(48,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(64,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(82,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(100,27): error CS0246: The type or namespace name 'IRestResponse<>' could not be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      FWO.Report -> /usr/local/fworch/lib/files/FWO.Report/bin/Release/net6.0/FWO.Report.dll
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
fworch-srv                 : ok=202  changed=134  unreachable=0    failed=1    skipped=115  rescued=0    ignored=0   

Error: Process completed with exit code 2.
```

**Comment by tpurschke** [comment]
completed
