### PR TITLE
New lib versions + github action fix

### LINKED ISSUE #2067: UI error during install on github
introduced by https://github.com/CactuseSecurity/firewall-orchestrator/pull/2065 (json export for resolved changes)

action: https://github.com/CactuseSecurity/firewall-orchestrator/actions/runs/5006117133

not seen on local installs

same errors also occur for certification.razor page
```
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1544,150): error CS0400: The type or namespace name 'TabSet' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(218,55): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.TabSet' to 'TabSet?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1553,158): error CS0400: The type or namespace name 'AnchorNavToRSB' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(218,82): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.AnchorNavToRSB' to 'AnchorNavToRSB?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Microsoft.NET.Sdk.Razor.SourceGenerators/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/Pages_Reporting_Report_razor.g.cs(1603,150): error CS0400: The type or namespace name 'TabSet' could not be found in the global namespace (are you missing an assembly reference?) [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
    /usr/local/fworch/ui/files/FWO.UI/Pages/Reporting/Report.razor(219,47): error CS1503: Argument 1: cannot convert from 'FWO.Ui.Shared.TabSet' to 'TabSet?' [/usr/local/fworch/ui/files/FWO.UI/FWO.Ui.csproj]
```

#### There seems to be an issue with the standard rule report
Now got a second error during debugging when generating rule report:

```
Exception has occurred: CLR/System.NullReferenceException
An exception of type 'System.NullReferenceException' occurred in FWO.Report.dll but was not handled in user code: 'Object reference not set to an instance of an object.'
   at FWO.Ui.Display.RuleDisplayHtml.NetworkLocationToHtml(NetworkLocation userNetworkObject, Int32 mgmtId, OutputLocation location, String style, ReportType reportType) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 103
   at FWO.Ui.Display.RuleDisplayHtml.<>c__DisplayClass13_0.<DisplaySourceOrDestination>b__0(NetworkLocation networkLocation) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 132
   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
   at FWO.Ui.Display.RuleDisplayHtml.DisplaySourceOrDestination(Rule rule, OutputLocation location, ReportType reportType, String style, Boolean isSource) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 132
   at FWO.Ui.Display.RuleDisplayHtml.DisplayDestination(Rule rule, OutputLocation location, ReportType reportType, String style) in /home/tim/dev/firewall-orchestrator/roles/lib/files/FWO.Report/Display/RuleDisplayHtml.cs:line 28
   at FWO.Ui.Pages.Reporting.Reports.RulesReport.<>c__DisplayClass0_12.<BuildRenderTree>b__61(RenderTreeBuilder __builder5) in /home/tim/dev/firewall-orchestrator/roles/ui/files/FWO.UI/Pages/Reporting/Reports/RulesReport.razor:line 131
   at BlazorTable.Table`1.BuildRenderTree(RenderTreeBuilder __builder)
   at Microsoft.AspNetCore.Components.ComponentBase.<.ctor>b__6_0(RenderTreeBuilder builder)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& 
```

And also during rule report generation in a fresh install in the browser:
```
razor.server.js:1 [2023-05-18T11:28:12.414Z] Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions by setting 'DetailedErrors: true' in 'appSettings.Development.json' or set 'CircuitOptions.DetailedErrors'. 
log @ blazor.server.js:1
blazor.server.js:1 [2023-05-18T11:28:12.415Z] Information: Connection disconnected.
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52089)
    at kt._sendMessage (blazor.server.js:1:68724)
    at kt._sendWithProtocol (blazor.server.js:1:68765)
    at kt.send (blazor.server.js:1:68873)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:131829)
    at w (blazor.server.js:1:2164)
    at C.invokeMethodAsync (blazor.server.js:1:4014)
    at window.js:14:70
blazor.server.js:1 Uncaught (in promise) Error: Cannot send data if the connection is not in the 'Connected' State.
    at bt.send (blazor.server.js:1:52089)
    at kt._sendMessage (blazor.server.js:1:68724)
    at kt._sendWithProtocol (blazor.server.js:1:68765)
    at kt.send (blazor.server.js:1:68873)
    at Object.beginInvokeDotNetFromJS (blazor.server.js:1:131829)
    at w (blazor.server.js:1:2164)
    at C.invokeMethodAsync (blazor.server.js:1:4014)
    at window.js:10:71
```

### PR DESCRIPTION
**Pull request by NilsPur**
closes #2067

### CODE REVIEW

**Review by tpurschke — CHANGES_REQUESTED** [review]
apart from the usual error on ubuntu 22.04, we now get the following errors during github actions test install on ubuntu 20.04:
```

TASK [middleware : publish middlewareserver] ***********************************
fatal: [localhost]: FAILED! => changed=true 
  cmd:
  - dotnet
  - publish
  - --no-self-contained
  - -c
  - Release
  - -o
  - /usr/local/fworch/middleware/files/FWO.Middleware.Server/bin/Release/net6.0
  delta: '0:00:17.407009'
  end: '2023-05-22 19:03:45.184654'
  msg: non-zero return code
  rc: 1
  start: '2023-05-22 19:03:27.777645'
  stderr: ''
  stderr_lines: <omitted>
  stdout: |-
    MSBuild version 17.6.1+8ffc3fe3d for .NET
      Determining projects to restore...
      Restored /usr/local/fworch/lib/files/FWO.Report.Filter/FWO.Report.Filter.csproj (in 1.75 sec).

[snip]

      FWO.Config.Api -> /usr/local/fworch/lib/files/FWO.Config.Api/bin/Release/net6.0/FWO.Config.Api.dll
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(27,24): error CS1061: 'RestClient' does not contain a definition for 'UseDefaultSerializers' and no accessible extension method 'UseDefaultSerializers' accepting a first argument of type 'RestClient' could be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FortiManagerAPI.cs(28,24): error CS1061: 'RestClient' does not contain a definition for 'UseSerializer' and no accessible extension method 'UseSerializer' accepting a first argument of type 'RestClient' could be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(27,24): error CS1061: 'RestClient' does not contain a definition for 'UseDefaultSerializers' and no accessible extension method 'UseDefaultSerializers' accepting a first argument of type 'RestClient' could be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(28,24): error CS1061: 'RestClient' does not contain a definition for 'UseSerializer' and no accessible extension method 'UseSerializer' accepting a first argument of type 'RestClient' could be found (are you missing a using directive or an assembly reference?) [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
    /usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/CheckPointAPI.cs(36,28): error CS7036: There is no argument given that corresponds to the required parameter 'request' of 'RestResponse<CpSessionAuthInfo>.RestResponse(RestRequest)' [/usr/local/fworch/lib/files/FWO.DeviceAutoDiscovery/FWO.DeviceAutoDiscovery.csproj]
      FWO.Report -> /usr/local/fworch/lib/files/FWO.Report/bin/Release/net6.0/FWO.Report.dll
  stdout_lines: <omitted>

PLAY RECAP *********************************************************************
localhost                  : ok=142  changed=94   unreachable=0    failed=1    skipped=80   rescued=0    ignored=0   

Error: Process completed with exit code 2.

```

**Review by tpurschke — APPROVED** [review]
install works fine on local ubuntu 20 and 22
github install works on ubuntu 20 only
